### ISSUE TITLE
Change Natural logarithm in x-axis of volcano plot to base2 logarithm

### ISSUE THREAD

**Issue by ropolomx** [BeeCSI-Microbiome/R_analyses#15]
https://github.com/BeeCSI-Microbiome/R_analyses/blob/63fb3f957f2591333be2587cad909f052ace4218/JonathanH/test_ANCOMBC.R#L161

Log2 is usually the way to transform the fold-change results in volcano plot. Natural logarithm is not typically used. Please confirm if log2 (base 2 logarithm) is what is being used, or if it is the natural logarithm (ln, which is logarithm using the number e as the base).

**Comment by jonathho** [comment]
Hi @ropolomx , I believe it is the natural log being used as per the author/developer's [github issue](https://github.com/FrederickHuangLin/ANCOMBC/issues/11#issuecomment-878864987). The plot takes the logfoldchange values from the ancom-bc output, but we could transform to base 2 if we want though.

**Comment by LLansing** [comment]
When we use log base 2 then along the x-axis, -1 and 1 represent a twofold magnitude difference, -2 and 2 represent a fourfold magnitude difference, and so on. I think this is more intuitive than natural log, where -1 and 1 would be a e-fold magnitude difference (~2.718 fold).

**Comment by LLansing** [comment]
Changed code to create a log2 column for ANCOM magnitude values, and to use log2 values for volcano plots
