### ISSUE TITLE
Modify fold change to be log base 2 instead of base e

### ISSUE THREAD

**Issue by jonathho** [BeeCSI-Microbiome/R_analyses#16]
Now that the results have been verified to be consistent across the implementations (test_ANCOMBC.R and da-ancombc.R) we can safely modify the log fold-change (called beta in ancombc) to be base 2 for comparisons across other studies, and or ease of interpretation.
This change of base would probably be best done on line 119 in da-ancombc.R so that the change would be reflected in both the volcano plot and the saved csv file. https://github.com/BeeCSI-Microbiome/R_analyses/blob/1b0f99d6c645f927ade23cbdfbbbd89cf524f122/scripts/snippets/da-ancombc.R#L119
Also remember to change the x-axis label in the plot: https://github.com/BeeCSI-Microbiome/R_analyses/blob/1b0f99d6c645f927ade23cbdfbbbd89cf524f122/scripts/snippets/da-ancombc.R#L159

**Comment by LLansing** [comment]
Changed code to create a log2 column for ANCOM magnitude values, and to use log2 values for volcano plots
